"""Repository readiness analysis.

Given the set of committed files (config-relative) and the committed ``.gitignore``,
decide whether the repo looks like a Home Assistant config repo and whether it's safe
to deploy from. Deployment is gated on *zero blockers*; the numeric score is for UX.
"""
from __future__ import annotations

import pathspec

from ..models import Finding, ReadinessReport, Severity

# (code, title, patterns, suggestion)
BLOCKER_RULES: list[tuple[str, str, list[str], str]] = [
    (
        "secrets_committed",
        "secrets.yaml is committed",
        ["secrets.yaml", "**/secrets.yaml"],
        "Remove it from the repo, purge it from history, add it to .gitignore, and "
        "commit a secrets.yaml.example instead. Treat the leaked secrets as compromised.",
    ),
    (
        "database_committed",
        "Database files are committed",
        ["*.db", "*.db-wal", "*.db-shm", "*.sqlite", "**/*.db", "**/*.sqlite"],
        "The recorder database is large, binary and instance-specific. Remove it and "
        "add `*.db*` / `*.sqlite` to .gitignore.",
    ),
    (
        "storage_committed",
        ".storage is committed",
        [".storage", ".storage/**"],
        ".storage holds auth tokens, the entity/device registry and UI dashboards. "
        "Remove it and add `.storage/` to .gitignore.",
    ),
    (
        "tokens_committed",
        "Token / credential files are committed",
        ["*.token", ".google.token", "**/*.token"],
        "Remove credential files from the repo and add them to .gitignore.",
    ),
    (
        "cloud_committed",
        ".cloud is committed",
        [".cloud", ".cloud/**"],
        "Remove the .cloud directory and add `.cloud/` to .gitignore.",
    ),
    (
        "backups_committed",
        "Backups / archives are committed",
        ["backups", "backups/**", "*.tar", "*.tar.gz", "*.tgz"],
        "Backups can contain secrets and are large. Remove them and add `backups/` and "
        "`*.tar*` to .gitignore.",
    ),
]

WARNING_RULES: list[tuple[str, str, list[str], str]] = [
    (
        "logs_committed",
        "Log files are committed",
        ["*.log", "**/*.log", "*.log.*", "**/*.log.*"],
        "Logs contain runtime/personal data. Add `*.log` and `*.log.*` to .gitignore.",
    ),
    (
        "runtime_artifacts",
        "Home Assistant runtime artifacts are committed",
        [".HA_VERSION", ".ha_run.lock", ".uuid"],
        "These are generated by Home Assistant. Add them to .gitignore.",
    ),
    (
        "cache_committed",
        "Cache / dependency directories are committed",
        ["deps", "deps/**", "tts", "tts/**", "__pycache__/**", "**/__pycache__/**"],
        "These are regenerated at runtime. Add `deps/`, `tts/`, `__pycache__/` to .gitignore.",
    ),
    (
        "privacy_files",
        "Files containing personal data are committed",
        ["known_devices.yaml", "ip_bans.yaml"],
        "These contain MAC/IP data. Consider adding them to .gitignore.",
    ),
    (
        "custom_components",
        "custom_components is committed",
        ["custom_components/**"],
        "These are usually managed by HACS. Add `custom_components/` to .gitignore "
        "unless you intentionally vendor them.",
    ),
]

# .gitignore entries we consider essential.
CRITICAL_GITIGNORE = ["secrets.yaml", ".storage/", "*.db"]


def _matches(patterns: list[str], paths: list[str]) -> list[str]:
    spec = pathspec.GitIgnoreSpec.from_lines(patterns)
    return sorted(p for p in paths if spec.match_file(p))


def analyze(
    tracked_paths: list[str],
    gitignore_text: str | None,
    is_empty: bool,
    storage_dashboards: bool = False,
) -> ReadinessReport:
    findings: list[Finding] = []

    if is_empty:
        findings.append(
            Finding(
                code="empty_repo",
                severity=Severity.RECOMMENDATION,
                title="Repository is empty",
                detail="This repository has no commits yet.",
                suggestion="Use “Initialize Repository From Current Home Assistant "
                "Configuration” to populate it safely.",
            )
        )
        return ReadinessReport(is_empty=True, is_valid_repo=False, score=0, findings=findings)

    paths = list(tracked_paths)
    has_config = "configuration.yaml" in paths
    is_valid = has_config

    if not has_config:
        findings.append(
            Finding(
                code="missing_configuration_yaml",
                severity=Severity.BLOCKER,
                title="Missing configuration.yaml",
                detail="No configuration.yaml was found at the selected config path.",
                suggestion="Point the config path at the directory containing "
                "configuration.yaml, or add one.",
            )
        )

    for code, title, patterns, suggestion in BLOCKER_RULES:
        hits = _matches(patterns, paths)
        if hits:
            findings.append(
                Finding(
                    code=code,
                    severity=Severity.BLOCKER,
                    title=title,
                    detail=f"{len(hits)} matching file(s) are committed.",
                    suggestion=suggestion,
                    paths=hits[:25],
                )
            )

    for code, title, patterns, suggestion in WARNING_RULES:
        hits = _matches(patterns, paths)
        if hits:
            findings.append(
                Finding(
                    code=code,
                    severity=Severity.WARNING,
                    title=title,
                    detail=f"{len(hits)} matching file(s) are committed.",
                    suggestion=suggestion,
                    paths=hits[:25],
                )
            )

    # .gitignore checks.
    if ".gitignore" not in paths:
        findings.append(
            Finding(
                code="missing_gitignore",
                severity=Severity.WARNING,
                title="Missing .gitignore",
                detail="No .gitignore — sensitive/runtime files could be committed by accident.",
                suggestion="Add a Home Assistant .gitignore (the add-on can generate one).",
            )
        )
    elif gitignore_text is not None:
        entries = {
            ln.strip()
            for ln in gitignore_text.splitlines()
            if ln.strip() and not ln.strip().startswith("#")
        }
        missing = [e for e in CRITICAL_GITIGNORE if e not in entries]
        if missing:
            findings.append(
                Finding(
                    code="weak_gitignore",
                    severity=Severity.WARNING,
                    title=".gitignore is missing critical entries",
                    detail="Missing: " + ", ".join(missing),
                    suggestion="Add the missing entries to protect secrets and the database.",
                )
            )

    if "secrets.yaml.example" not in paths:
        findings.append(
            Finding(
                code="missing_secrets_example",
                severity=Severity.WARNING,
                title="Missing secrets.yaml.example",
                detail="No template documenting which secrets the config expects.",
                suggestion="Add secrets.yaml.example listing required keys with blank values.",
            )
        )

    if "README.md" not in paths and "readme.md" not in paths:
        findings.append(
            Finding(
                code="missing_readme",
                severity=Severity.RECOMMENDATION,
                title="No README.md",
                detail="A README helps document the configuration.",
                suggestion="Add a README.md.",
            )
        )

    # Dashboards live in .storage (UI/"storage" mode) by default, which can't be
    # safely versioned. Nudge the user toward YAML mode so dashboards become
    # editable files an AI can build and HA-GitOps can deploy.
    if storage_dashboards:
        has_yaml_dash = any(
            p == "ui-lovelace.yaml" or p.startswith(("lovelace/", "dashboards/"))
            for p in paths
        )
        if not has_yaml_dash:
            findings.append(
                Finding(
                    code="dashboards_in_storage",
                    severity=Severity.RECOMMENDATION,
                    title="Dashboards are in UI (storage) mode — not versioned",
                    detail="Lovelace dashboards are stored in .storage as JSON, not "
                    "YAML, so they aren't committed and an AI can't edit them as files.",
                    suggestion="Switch dashboards to YAML mode to version them (see DOCS "
                    "→ “Making dashboards versionable”). Automations/scripts/scenes are "
                    "already YAML and are versioned.",
                )
            )

    score = 100
    for f in findings:
        if f.severity is Severity.BLOCKER:
            score -= 30
        elif f.severity is Severity.WARNING:
            score -= 8
        else:
            score -= 2
    score = max(0, min(100, score))

    return ReadinessReport(
        is_empty=False, is_valid_repo=is_valid, score=score, findings=findings
    )
