"""Home Assistant → GitHub synchronization: manual push and empty-repo init."""
from __future__ import annotations

import asyncio
import logging
import shutil
from pathlib import Path
from typing import TYPE_CHECKING

import yaml

from .. import settings
from ..models import DeployResult, DeployStatus, Direction, SyncState
from . import conflicts, filesync, validator

if TYPE_CHECKING:
    from .engine import Engine

log = logging.getLogger("ha_gitops.sync")

RECOMMENDED_GITIGNORE = """\
# Home Assistant — generated by HA-GitOps
# Secrets & credentials
secrets.yaml
*.token
.google.token
.cloud/
ip_bans.yaml
known_devices.yaml

# Databases & history
*.db
*.db-shm
*.db-wal
*.sqlite

# Runtime state & system files
.storage/
.HA_VERSION
.ha_run.lock
.uuid

# Logs
*.log

# Caches & dependencies
deps/
tts/
__pycache__/

# Backups & archives
backups/
*.tar
*.tar.gz

# Custom components are usually managed by HACS
custom_components/

# OS / editor
.DS_Store
.vscode/
"""


def _secrets_example(secrets_path: Path) -> str:
    header = (
        "# secrets.yaml.example — generated by HA-GitOps\n"
        "# Copy to secrets.yaml and fill in real values. Do NOT commit secrets.yaml.\n"
    )
    keys: list[str] = []
    if secrets_path.is_file():
        try:
            data = yaml.safe_load(secrets_path.read_text(encoding="utf-8")) or {}
            if isinstance(data, dict):
                keys = list(data.keys())
        except (yaml.YAMLError, OSError):
            pass
    if not keys:
        return header + 'some_api_key: ""\n'
    return header + "".join(f'{k}: ""\n' for k in keys)


class SyncEngine:
    def __init__(self, engine: Engine) -> None:
        self.e = engine

    def _repo_cfg(self) -> Path:
        cp = self.e.require_connection().config_path.strip("/")
        return settings.REPO_DIR / cp if cp else settings.REPO_DIR

    # ---- HA -> GitHub push --------------------------------------------------
    async def push(self, message: str) -> DeployResult:
        e = self.e
        conn = e.require_connection()
        tok = e.require_token()
        result = DeployResult(
            status=DeployStatus.IN_PROGRESS, branch=conn.branch, direction=Direction.PUSH
        )

        if e.state.last_remote_sha is None:
            result.status = DeployStatus.SKIPPED
            result.message = "Repository is empty — use Initialize instead."
            return result

        changes = await e.detect_changes()
        if not changes.dirty:
            result.status = DeployStatus.SKIPPED
            result.message = "No local changes to push."
            return result

        # Block on a true conflict (remote also moved).
        await e.git.fetch(conn.branch, tok)
        remote = await e.git.remote_head(conn.branch)
        if remote is None:
            result.status = DeployStatus.SKIPPED
            result.message = "Remote branch not found on GitHub; cannot push."
            return result
        state = conflicts.evaluate(e.state.sync_base_sha, remote, True, repo_empty=False)
        if state is SyncState.CONFLICT:
            e.state.record_conflict(e.state.sync_base_sha, remote, conflicts.summarize_local(changes))
            await e.notifier.conflict(e.state.sync_base_sha or "", remote or "", changes.count)
            result.status = DeployStatus.SKIPPED
            result.message = "Conflict: GitHub changed too. Resolve before pushing."
            return result

        # Validate before pushing (never push broken config).
        errors = await self._validate_live()
        if errors:
            result.status = DeployStatus.VALIDATION_FAILED
            result.errors = errors
            result.message = "Local configuration is invalid; not pushing."
            e.state.log_event("error", "sync", result.message)
            return result

        deployment_id = e.state.record_deployment(
            Direction.PUSH.value, None, conn.branch, DeployStatus.IN_PROGRESS.value
        )
        result.deployment_id = deployment_id
        try:
            await e.git.reset_to(conn.branch, remote)
            dest = self._repo_cfg()
            guard = filesync.build_ignore_spec(None)  # ALWAYS_IGNORE only
            applied = await asyncio.to_thread(
                self._copy_changes_into_repo, changes, dest, guard
            )
            result.files_changed = applied

            await e.git.stage_all(conn.config_path)
            if not await e.git.has_staged_changes():
                result.status = DeployStatus.SKIPPED
                result.message = "Nothing to commit after filtering."
                e.state.finish_deployment(deployment_id, status=result.status.value, message=result.message)
                return result

            new_sha = await e.git.commit(message or "Sync Home Assistant local configuration changes")
            await e.git.push(conn.branch, tok)

            await self._mark_synced(new_sha)
            result.status = DeployStatus.SUCCESS
            result.sha = new_sha
            result.message = f"Pushed {applied} file(s) as {new_sha[:8]}."
            e.state.finish_deployment(
                deployment_id, status=result.status.value, sha=new_sha,
                files_changed=applied, message=result.message,
            )
            e.state.log_event("info", "sync", result.message)
            return result
        except Exception as exc:  # noqa: BLE001
            result.status = DeployStatus.FAILED
            result.errors = [str(exc)]
            result.message = f"Push failed: {exc}"
            e.state.finish_deployment(deployment_id, status=result.status.value, errors=result.errors, message=result.message)
            e.state.log_event("error", "sync", result.message)
            return result

    def _copy_changes_into_repo(self, changes, dest: Path, guard) -> int:
        count = 0
        for rel in changes.modified + changes.added:
            if guard.match_file(rel):
                continue
            src = settings.HA_CONFIG_DIR / rel
            if not src.is_file():
                continue
            target = dest / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, target)
            count += 1
        for rel in changes.deleted:
            if guard.match_file(rel):
                continue
            target = dest / rel
            if target.exists():
                target.unlink()
                count += 1
        return count

    # ---- empty repo initialization -----------------------------------------
    async def initialize(self) -> DeployResult:
        e = self.e
        conn = e.require_connection()
        tok = e.require_token()
        result = DeployResult(
            status=DeployStatus.IN_PROGRESS, branch=conn.branch, direction=Direction.INIT
        )

        await e.git.fetch(conn.branch, tok)
        if await e.git.remote_head(conn.branch) is not None:
            result.status = DeployStatus.SKIPPED
            result.message = "Repository is not empty; initialization is only for empty repos."
            return result

        deployment_id = e.state.record_deployment(
            Direction.INIT.value, None, conn.branch, DeployStatus.IN_PROGRESS.value
        )
        result.deployment_id = deployment_id
        try:
            dest = self._repo_cfg()
            copied = await asyncio.to_thread(self._populate_initial_repo, dest)
            result.files_changed = copied

            await e.git.stage_all(conn.config_path)
            if not await e.git.has_staged_changes():
                result.status = DeployStatus.FAILED
                result.message = "Nothing to commit — is the Home Assistant config empty?"
                e.state.finish_deployment(deployment_id, status=result.status.value, message=result.message)
                return result

            new_sha = await e.git.commit(
                "Initialize repository from current Home Assistant configuration"
            )
            await e.git.rename_branch(conn.branch)
            await e.git.push(conn.branch, tok, set_upstream=True)

            await self._mark_synced(new_sha)
            result.status = DeployStatus.SUCCESS
            result.sha = new_sha
            result.message = f"Initialized repository with {copied} file(s) ({new_sha[:8]})."
            e.state.finish_deployment(
                deployment_id, status=result.status.value, sha=new_sha,
                files_changed=copied, message=result.message,
            )
            e.state.log_event("info", "sync", result.message)
            return result
        except Exception as exc:  # noqa: BLE001
            result.status = DeployStatus.FAILED
            result.errors = [str(exc)]
            result.message = f"Initialization failed: {exc}"
            e.state.finish_deployment(deployment_id, status=result.status.value, errors=result.errors, message=result.message)
            e.state.log_event("error", "sync", result.message)
            return result

    def _populate_initial_repo(self, dest: Path) -> int:
        dest.mkdir(parents=True, exist_ok=True)
        # Generate .gitignore and secrets.yaml.example first.
        (dest / ".gitignore").write_text(RECOMMENDED_GITIGNORE)
        (dest / "secrets.yaml.example").write_text(
            _secrets_example(settings.HA_CONFIG_DIR / "secrets.yaml")
        )
        spec = filesync.build_ignore_spec(RECOMMENDED_GITIGNORE)
        count = 2
        for rel in filesync._walk_relpaths(settings.HA_CONFIG_DIR, spec):
            if spec.match_file(rel):
                continue
            src = settings.HA_CONFIG_DIR / rel
            if not src.is_file():
                continue
            target = dest / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, target)
            count += 1
        return count

    # ---- shared -------------------------------------------------------------
    async def _validate_live(self) -> list[str]:
        e = self.e
        if e.supervisor.available:
            vr = await e.supervisor.check_config()
            return [] if vr.ok else vr.errors
        # Fallback when there's no Supervisor (dev/test): Layer-1 on the live dir.
        vr = await asyncio.to_thread(
            validator.validate_config_dir,
            settings.HA_CONFIG_DIR,
            settings.HA_CONFIG_DIR / "secrets.yaml",
        )
        return [] if vr.ok else vr.errors

    async def _mark_synced(self, new_sha: str) -> None:
        e = self.e
        conn = e.require_connection()
        e.state.last_deployed_sha = new_sha
        e.state.sync_base_sha = new_sha
        e.state.last_remote_sha = new_sha
        e.state.set(e._etag_key(conn), None)  # force a fresh read next poll
        tracked = await e.git.ls_tree(new_sha, conn.config_path)
        manifest = await asyncio.to_thread(
            filesync.build_manifest, list(tracked.keys()), settings.HA_CONFIG_DIR
        )
        e.state.set_manifest(manifest)
        e.state.clear_open_conflicts("synced")
